### PR TITLE
 cleanup(contributors-script): remove unnecessary code and handle http errors

### PR DESCRIPTION
**Pull request by GabsEdits**
~~I will keep this Pull Request as a draft till Vanilla-OS/website#176 gets merged.~~

### CODE REVIEW

**Comment by GabsEdits** [comment]
The pull request builds up conflicts with `contributors.json` because of the difference of how the file is structured, I will resolve the conflicts once https://github.com/Vanilla-OS/website/pull/176 gets merged :+1: 

For now, I will disable the action so there won't be a new `chore` commit every week inside the Pull Request.

**Comment by kbdharun** [comment]
@GabsEdits Hi, Is this open for review? (any changes still to work on?)

**Comment by GabsEdits** [comment]
> @GabsEdits Hi, Is this open for review? (any changes still to work on?)

It's open for review yes. I've set it to draft to avoid being merged before https://github.com/Vanilla-OS/website/pull/176 (as it will break the current page on the website). I can open it for review if it's needed

**Comment by GabsEdits** [comment]
https://github.com/Vanilla-OS/website/pull/176 has just been merged. I will resolve the conflicts with the .json file

**Comment by GabsEdits** [comment]
The Pull Request is ready to be merged.

**Review by kbdharun — CHANGES_REQUESTED** [review]
The current/latest version of the contributors file seems to be missing the `avatar_url` and `profile_url` parameters.

**Comment by GabsEdits** [comment]
> The current/latest version of the contributors file seems to be missing the `avatar_url` and `profile_url` parameters.

That's by design. Both the `avatar_url` and `profile_url` aren't necessary, and are now handled by the front-end with the merge of https://github.com/Vanilla-OS/website/pull/176.

Edit: You can see why they aren't needed in this script by checking [Line 10 & 12 in Contributors.vue](https://github.com/Vanilla-OS/website/blob/v2/src/views/get-involved/Contributors.vue#L10-L12)

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
